version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs:3.35_large_disk_full # use a remote dev image
    container_name: master
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    networks:
      - ttcntt
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
  volume:
    image: chrislusf/seaweedfs:3.35_large_disk_full # use a remote dev image
    container_name: volume
    ports:
      - 8900:8080
      - 18080:18080
      - 9325:9325
    networks:
      - ttcntt
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:3.35_large_disk_full # use a remote dev image
    container_name: filter
    ports:
      - 8901:8888
      - 18888:18888
      - 9326:9326
    networks:
      - ttcntt
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:3.35_large_disk_full # use a remote dev image
    container_name: s3
    ports:
      - 8333:8333
      - 9327:9327
    networks:
      - ttcntt
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327'
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs:3.35_large_disk_full # use a remote dev image
    container_name: webdav
    ports:
      - 7333:7333
    networks:
      - ttcntt
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer

  # only for testing, not related seaweedfs
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - '2181:2181'
      - '8902:8080'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # ZOOKEEPER_ADMIN_ENABLE_SERVER: false
    networks:
      - ttcntt

# we should create new bridge network, we may get error when using default bridge network
networks:
  ttcntt:
    name: 'ttcntt'
    driver: 'bridge'